# Generated by Django 5.1.15 on 2026-08-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localuser',
            name='is_indian_resident',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
